inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    - "config/rails.yml"
    # uncomment if use rspec cops
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.4
  # uncomment if use rails cops
  TargetRailsVersion: 5.1
  Exclude:
    - "frontend/*.*"

Style/GlobalVars:
  Exclude:
    - "config/unicorn/*.rb"

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "Gemfile"
    - "Guardfile"
    - "config/environments/*.rb"
    - "config/routes.rb"
    - "config/routes/**/*.rb"
    - "config/deploy.rb"  # ADD
    - "*.gemspec"

Lint/HandleExceptions:
  Exclude:
    - "config/unicorn/production.rb"  # 何やってるのかよくわからんのでとりあえずExclude
    - "config/unicorn/staging.rb"  # 何やってるのかよくわからんのでとりあえずExclude

Naming/AccessorMethodName:
  Exclude:
    - "app/services/podcast/feed.rb"

Rails:
  Exclude:
    - "config/sitemap.rb"

Rails/OutputSafety:
  Exclude:
    - "app/helpers/markdown_helper.rb" # markdownをparseした結果を返すのにhtml_safeは必須
