declare module "*.css";
declare module "*.png";
declare module "*.jpg";
declare module "*.gif";
declare module "*.eot";
declare module "*.svg";
declare module "*.ttf";
declare module "*.woff";
declare module "*.woff2";
