# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.2-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
       - image: circleci/mysql:8.0.2
         environment:
           MYSQL_USER: 'root'
           MYSQL_ROOT_PASSWORD: 'root'
           MYSQL_ROOT_HOST: '%'

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rake db:create db:schema:load RAILS_ENV=test --trace

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            bundle exec rspec spec/ --format progress \
                            --out ./tmp/test-results/rspec.xml \
                            --format progress \

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  frontend-build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.8.1
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: |
            cd frontend
            yarn install --frozen-lockfile --prefer-offline
      - run:
          name: yarn test
          command: |
            cd frontend
            yarn build

  frontend-test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.8.1
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: |
            cd frontend
            yarn install --frozen-lockfile --prefer-offline
      - run:
          name: yarn test
          command: |
            cd frontend
            yarn test

workflows:
  version: 2
  main:
    jobs:
      - build
      - frontend-build
      - frontend-test
